version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: preprod

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: preprod

  - package-ecosystem: docker
    directory: /build-container
    schedule:
      interval: daily
    target-branch: preprod
