version: "3.3"
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - "./testData.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - POSTGRES_PASSWORD=toto
      - POSTGRES_HOST_AUTH_METHOD=trust
  wekandb:
    image: mongo:5
    #-------------------------------------------------------------------------------------
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - wekan-db:/data/db
      - wekan-db-dump:/dump
  wekan:
    image: quay.io/wekan/wekan:v6.61
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 8081:8080
    environment:
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=true
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekandb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - wekan-files:/data:rw
volumes:
  testData.sql:
  wekan-files:
    driver: local
  wekan-db:
    driver: local
  wekan-db-dump:
    driver: local
networks:
  wekan-tier: