name: CI

on:
  push:
    branches:
      - 'master'
      - 'feat-*'
      - 'feat/*'
  pull_request:
    branches: [ master ]

jobs:
  build_datapi:
    name: Build & Test Datapi
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
      id: go

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Build package
      run: go build -v .

    - name: Install docx-mailmerge
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install docx-mailmerge

    - name: Unit Tests
      run: go test ./...

    - name: Integration Tests
      run: go test -tags=integration
