name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
on:
  push:
    branches: [ try_to_push_to_registry ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build binary
        shell: bash
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build
          cp ./datapi ./build-container
          cp -r ./migrations ./build-container

      - name: Build container image
        shell: bash
        run: |
          docker build -t datapi --build-arg datapiDir="." ./build-container

      - name: Push container image
        uses: docker/build-push-action@v2
        with:
          context: ./build-container
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest