name: e2e test

on:
  push:
    branches: [ master, datapi_v2 ]
  pull_request:
    branches: [ master, datapi_v2 ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .
      
    - name: Test
      run: |
        cd test
        bash ./test.sh
